{% set version = "1.0.1" %}

package:
  name: moto
  version: {{ version }}

source:
  fn: moto-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/m/moto/moto-{{ version }}.tar.gz
  sha256: 1e856ff6c2ec03785b7ac758c2564b1644a5fe02ce00e5653b5a94e71af9532f

build:
  entry_points:
    - moto_server = moto.server:main
  skip: False

requirements:
  build:
    - python
    - setuptools
    - jinja2
    - boto >=2.20.0
    - flask
    - httpretty >=0.6.1
    - requests
    - xmltodict
    - six
    - werkzeug

  run:
    - python
    - jinja2
    - boto >=2.20.0
    - flask
    - httpretty >=0.6.1
    - requests
    - xmltodict
    - six
    - werkzeug

test:
  imports:
    - moto
    - moto.autoscaling
    - moto.cloudformation
    - moto.cloudwatch
    - moto.core
    - moto.datapipeline
    - moto.dynamodb
    - moto.dynamodb2
    - moto.ec2
    - moto.ec2.responses
    - moto.elb
    - moto.emr
    - moto.glacier
    - moto.iam
    - moto.kinesis
    - moto.kms
    - moto.rds
    - moto.rds2
    - moto.redshift
    - moto.route53
    - moto.s3
    - moto.s3bucket_path
    - moto.ses
    - moto.sns
    - moto.sqs
    - moto.sts

  commands:
    - moto_server --help

about:
  home: https://github.com/spulec/moto
  license: Apache Software License
  summary: A library that allows your python tests to easily mock out the boto library.
